apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diploma-helm.name" . }}
  labels:
    {{- include "diploma-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "diploma-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "diploma-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.registry.url }}/{{ .Values.registry.id }}/{{ .Values.image.tag }}:{{ .Values.image.tag | default "latest" }}"