apiVersion: v1
kind: Service
metadata:
  name: {{ include "diploma-helm.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "diploma-helm.selectorLabels" . | nindent 4 }}
  ports:
      {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- end }}