imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

registry:
  url: cr.yandex
  id: ""

replicaCount: 1

image:
  name: devops-netology-diploma-app
  tag: "latest"

service:
  type: ClusterIP
  ports: 
    - name: zakamaldin-diploma-http
      protocol: TCP
      port: 80
      targetPort: 80

ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: zakamaldin.test
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: zakamaldin-diploma-http
              port:
                number: 80